Doc/functions
wecoach-ai/DatasetHandler pull request #9
Opened 2024-07-17 15:03 UTC by Shreshtth

- Added docstrings explaining each function.

2024-07-17 15:08 UTC, onlinejudge95 requested changes

2024-07-17 15:08 UTC, onlinejudge95 commented on entrypoint.py
>  def extract(path, scope, frame_cutoff):
Let's add type hints for these arguments

2024-07-17 15:08 UTC, onlinejudge95 commented on src/download.py
> +        path (str): The local directory path for the dataset.
type hints are already provided no need to add redundant info

2024-07-17 15:08 UTC, onlinejudge95 commented on src/download.py
> +        path (str): The local directory path for the dataset.
do it for all the functions

2024-07-17 15:08 UTC, onlinejudge95 commented on src/extract.py
> +    Get the set of frame indices to extract based on annotations.
Be descriptive as to what logic is being used in terms of `num_frames`

2024-07-17 15:08 UTC, onlinejudge95 commented on src/extract.py
> +    Get the set of frame indices to extract around annotated events with smoothing.
Be descriptive as to what logic is being used in terms of `num_frames`

2024-07-17 19:21 UTC, Shreshtth commented
@onlinejudge95 I've taken all points from the review in account. And committed the new code.

2024-07-17 19:39 UTC, onlinejudge95 requested changes
@Shreshtth I have solved the merge conflict. Update the docstrings for the new functions.

2024-07-18 07:17 UTC, onlinejudge95 approved these changes

2024-07-18 07:18 UTC, merged